In [1]:
def add(a,b):
    return a+b

In [2]:
class test:
    def __init__(self, sample):
        self.add = sample

In [3]:
t = test(add)

In [4]:
t.add(1,2)

3

In [1]:
import numpy as np

a = np.array([np.NINF, -100])
np.NINF * 100

-inf

In [6]:
a = [1,2,3,4]
for i, _ in enumerate(a):
    print(_)

1
2
3
4


In [5]:
from numpy.random import default_rng

rng = default_rng()
numbers = rng.choice(3, size=3, replace=False)

In [6]:
numbers

array([2, 1, 0])

In [1]:
import numpy as np
a = np.array([[1,1],[1,1]])
b = np.array([[1,1],[1,1]])

In [2]:
b = 2*b
b

array([[2, 2],
       [2, 2]])

In [4]:
a + b*2

array([[5, 5],
       [5, 5]])

In [5]:
distmap = np.ones((10, 10), dtype=int)*np.Infinity
distmap

array([[inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]])

In [6]:
1 > distmap[0,0]

False

In [12]:
a = np.array([[1,0],
[2,3],
[10,0]])
a

array([[ 1,  0],
       [ 2,  3],
       [10,  0]])

In [13]:
np.unravel_index(np.argmax(a), a.shape)

(2, 0)

In [30]:
a = np.arange(10, 100, 1)


4.545454545454546

In [36]:
osp = 0.25
l = np.arange(0, len(a), int(len(a)/(osp*len(a))))
a[l]

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])